backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "/static/files/"
public_folder: "/files/"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/pages/_content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Path", name: "path", widget: "hidden", default: "/" }
          - { label: Hero, name: hero, widget: markdown }
          - label: Companies
            name: companies
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Summary, name: summary, widget: string }
              - { label: Graphic, name: graphic, widget: image }
          - label: Building
            name: building
            widget: object
            fields:
              - { label: Coming, name: coming, widget: string }
              - { label: Location, name: location, widget: string }
              - { label: Photo, name: photo, widget: image }
          - label: Our Story
            name: our_story
            widget: object
            fields:
              - { label: Subheading, name: subheading, widget: string }
              - { label: Heading, name: heading, widget: string }
              - { label: Content, name: content, widget: markdown }
              - label: Photos
                name: photos
                widget: object
                fields: 
                  - { label: Photo 1, name: photo_1, widget: image }
                  - { label: Photo 2, name: photo_2, widget: image }
                  - { label: Photo 3, name: photo_3, widget: image }
                  - { label: Photo 4, name: photo_4, widget: image }
                  - { label: Photo 5, name: photo_5, widget: image }
                  - { label: Photo 6, name: photo_6, widget: image }
                  - { label: Photo 7, name: photo_7, widget: image }
