backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "/static/files/"
public_folder: "/files/"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/pages/_content/home.md"
        fields:
          - {
              label: "Content Type",
              name: "contentType",
              widget: "hidden",
              default: "home",
            }
          - { label: "Path", name: "path", widget: "hidden", default: "/home" }
          - { label: Hero, name: hero, widget: markdown }
          - label: Company
            name: company
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Summary, name: summary, widget: string }
              - { label: Graphic, name: graphic, widget: image }
          - label: Building
            name: building
            widget: object
            fields:
              - { label: Coming, name: coming, widget: string }
              - { label: Location, name: location, widget: string }
          - label: Our Story
            name: our_story
            widget: object
            fields:
              - { label: Subheading, name: subheading, widget: string }
              - { label: Heading, name: heading, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Photos, name: photos, widget: list, fields: [{ label: Photo, name: photo, widget: image }] }

